- plugins.json
Added ase, nwchem, codtools, plugin-template plugins
> added plugins

- plugins.json
Add `pip_url` and `plugin_info` to aiida-vasp entry
> update vasp plugin info

- plugins.json
Hello aiidateam,
I am writing a AiiDA plugin for  [CASTEP](CASTEP) and would like to register it in the registry. The plugin is still in early development stage though.
Best wishes,
Bonan Zhu
> Added plugin info of aiida-castep

- plugins.json
developed by aliaksandr.yakutovich@epfl.ch
> register aiida-raspa

- plugins.json
Hi I'm Abel,
I add the phonopy plugin to the repository.
I also add a lammps plugin that I am developing. It is still very simple but it already works for
simple potentials.
> Add phonopy and lammps plugins

- plugins.json
Change the state of the CASTEP plugin from _registered_ to _development_.
> Updated the state of CASTEP plugin

- plugins.json
> Gollum plugin

- plugins.json
Added Read the Docs documentation url to the CASTEP plugin.
> Added CASTEP plugin documentation url

- make_ghpages/make_pages.py
- make_ghpages/mod/templates/main_index.html
- make_ghpages/mod/templates/singlepage.html
- make_ghpages/static/css/style.css
- plugins.json
Also, typo fix in the kkr plugin
> Improving the human-readable information for the plugins

- plugins.json
typo setup.json aiida-fleur, plugin info was not found. also updated pip url
> typo in aiida-fleur setup.json 

- plugins.json
These are my plugins for creation of tight-binding models from first-principles calculations:
- aiida-optimize
- aiida-bands-inspect
- aiida-symmetry-representation
- aiida-strain
- aiida-tbmodels
- aiida-tbextraction
> Add registry entries for several plugins.

- .pre-commit-config.yaml
- .travis.yml
- make_ghpages/make_pages.py
- make_ghpages/requirements.txt
* make code python2/3 compatible
* run yapf formatter
* add linter
> Python3 compat

- plugins.json
Registering the UppASD plugin in the AiiDA registry. The plugin is in the initial stages of development.
> Add the UppASD plugin to the registry

- make_ghpages/make_pages.py
- make_ghpages/mod/templates/main_index.html
- make_ghpages/mod/templates/singlepage.html
- make_ghpages/requirements.txt
- plugins.json
This PR 
* cleans up the make_ghpages script (commit 1)
* adds processing of the AiiDA version (which is displayed in the index & the detail pages) (commit 2)
* adds missing plugin_info keys for 3 plugins
> Add aiida version

- plugins.json
Create entry for AiiDA-Plumed plugin
> Add entry for AiiDA-Plumed

- .travis.yml
> switch to python3.6 on travis

- .pre-commit-config.yaml
- .travis.yml
- make_ghpages/make_pages.py
- make_ghpages/mod/templates/main_index.html
- make_ghpages/mod/templates/singlepage.html
- make_ghpages/requirements.txt
+ fix travis which did not show the build failure in the PR
> fixes for python3 build

- README.md
- make_ghpages/make_pages.py
fix #59 
checks that specified entry points start with given entry point root.
> add entry point validation

- README.md
Update README to clarify which properties are required / optional.
> clarify optional/required properties

- .pre-commit-config.yaml
- .travis.yml
- make_ghpages/make_pages.py
- make_ghpages/mod/templates/main_index.html
- make_ghpages/mod/templates/singlepage.html
- make_ghpages/requirements.txt
- plugins.json
will likely also send a patch for the generator to parse `pyproject.toml` instead of the `setup.json`
> plugins: add aiida-graphql

- .github/workflows/main.yml
- README.md
* fix location of svg button
* adapt github workflow to new cli
> fix location of svg button

- plugins.json
This code is actually all from chrisjsewell/aiida-crystal17@1eab9635e81a29956b0113bc91e13d5a4ee4269d (because it was easier for development). But with this released, I'll eventually remove it all from there and fix chrisjsewell/aiida-crystal17#25
> add aiida-gulp

- plugins.json
point back to master after 1.0 release
> fix aiida-core branch

- plugins.json
This PR is update for aiida-phonopy plugin.
Previously aiida-phonopy was developed by @abelcarreras but now @atztogo mainly does the job. The aiida-phonopy github repository was moved from that under @abelcarreras to aiida-phonopy organization.
> Update for aiida-phonopy plugin

- aiida_registry/__init__.py
- aiida_registry/make_pages.py
- aiida_registry/mod/templates/base.html
- aiida_registry/mod/templates/main_index.html
- aiida_registry/mod/templates/singlepage.html
aiida plugin: extension of AiiDA provided through entry point
aiida (plugin) package: python package containing one or more AiiDA
plugins
> update naming to new convention

- plugins.json
documentation to come .. soon.
the plugin should be available with pip.
> finally add bigdft plugin

- aiida_registry/fetch_metadata.py
- plugins.json
> validate documentation url, if provided

- plugins.json
Hi! The Gaussian plugin (and formchk, cubegen) should be usable now. I will try to add tests ASAP as well. cheers
> Added the gaussian plugin

- README.md
- aiida_registry/fetch_metadata.py
- plugins.json
- tests/test_metadata.json
The "entry_point" key in the plugins.json file is renamed to
"entry_point_prefix", which better conveys its meaning.
> replace entry_point => entry_point_prefix

- plugins.json
A collection of automated workflows to computer Wannier functions.
> aiida-wannier90-workflows

- .github/workflows/main.yml
since daily build with v1 started failing today
> update checkout action

- .pre-commit-config.yaml
- setup.py
The issue was on github actions... let's see whether this fixes things.
> try fixing toml version conflict with poetry

- aiida_registry/static/gotobutton.svg
- aiida_registry/static/logo.svg
fix #127 
@giovannipizzi So far, this only adds the logo to the gotobutton.
If we want to add the logo to the web site as well, we'll need to change the color scheme (at least the header).
Any preferences?
> add plugin registry logo

- plugins.json
I would like to register a scheduler plugin for the NIMS supercomputer.
> Added nims-scheduler

- plugins.json
All plugins and work chains developed at nanotech@surfaces will be moved to this repo.
> Add aiida-nanotech-empa plugin

- setup.py
github actions builds were failing with
pkg_resources.ContextualVersionConflict: (tomlkit 0.5.8 (/opt/hostedtoolcache/Python/3.7.8/x64/lib/python3.7/site-packages/tomlkit-0.5.8-py3.7.egg), Requirement.parse('tomlkit<0.6.0,>=0.5.11'), {'poetry'})
> fix toml dependency

- plugins.json
Dear all, I finally finished my plugin running VASP calculations through Custodian and I would like to add it to the aiida-registry
> Add aiida-cusp plugin

- README.md
> make code_home required

- plugins.json
I made minor updates of plugins.json for vasp and phonopy. I appreciate if you could merge it.
> Minor updates of plugins.json for vasp and phonopy

- plugins.json
Hi @ltalirz 
This PR aims to add `aiida-metavo-scheduler` to the registry.
> adding aiida-metavo-scheduler

- .github/workflows/webpage.yml
> don't run cronjob on forks

- plugins.json
Main code page: https://github.com/SUNCAT-Center/catmap
Code that automates descriptor based analysis - useful for catalysis
> Plugin for pure python code CatMAP

- plugins.json
Register aiida plugin for the spirit code (http://spirit-code.github.io)
> Register aiida-spirit plugin

- plugins.json
It is a placeholder for WIEN2k plugin. Thanks :)
> added WIEN2k

- README.md
- aiida_registry/fetch_metadata.py
- plugins.json
Use top-level key to replace explicit `name` key since it led to inconsistencies (and is unnecessary).
Also includes minor metadata fixes for some plugins.
> Simplify json

- plugins.json
See https://github.com/aiidalab/aiidalab-widgets-base/issues/205#issuecomment-908259571
> remove aiidalab-widgets-base

- plugins.json
Hi @ltalirz 
I've added the documentation urls for aforementioned plugins within this PR.
Cheers,
Pezhman
> Documentation url for `aiida-orca` and `aiida-supercell`

- plugins.json
I created a sleep command wrapper as an AiiDA calculation plugin.
> Add aiida-donothing calculaiton plugin

- plugins.json
We are working on a GROMACS plugin for AiiDA to make molecular dynamics simulation workflows using GROMACS available
> Added aiida-gromacs

- plugins.yaml
fix https://github.com/aiidateam/aiida-registry/issues/205
> fix aiida diff plugin info link

- plugins.yaml
fix https://github.com/aiidateam/aiida-registry/issues/212
it's no longer needed (superseded by aiida-pseudo) and more confusing
than helpful
> remove aiida-sssp

- plugins.yaml
Finally, it's here! An aiida plugin to calculate GW band structures using Wannier interpolation
> Add aiida-yambo-wannier90

- plugins.yaml
Added `pip_url` and `documentation_url`
> Update `aiida-dataframe` entry

- setup.py
poetry 1.2.0 changed some APIs
> fix poetry dependency

- plugins.yaml
`setup.json` :broken_heart:
`pyproject.toml` :heart:
> tweak: Switch to pyproject.toml in aiida-crystal-dft plugin

- plugins.yaml
An AiiDA plugin for high-throughput calculations of charged defects in solid-state systems
> Add aiida-defects

- plugins.yaml
Please we started a new plugin, can it be registered?
> Add aiida-muon

- aiida-registry-app/src/App.jsx
addresses #246 Add a green checkbox icon for plugins that installed successfully.
> Change checkbox icon

- aiida-registry-app/src/App.css
Fix the design issues on mobile screens.
> Fix the website design on small screens

- aiida_registry/static/gotobutton.svg
Restore the README figure deleted by mistake in #259
> Restore the readme figure

- aiida-registry-app/src/Components/MainIndex.jsx
It is not clear what is the use case of the green check mark and how it is generated.
In this PR I added an alert box that will appear with the technical explanation when the user clicks the check mark.
> Add Check mark technical information.

- aiida-registry-app/src/App.css
- aiida-registry-app/src/App.jsx
- aiida-registry-app/src/Components/Details.css
- aiida-registry-app/src/Components/Details.jsx
- aiida-registry-app/src/Components/MainIndex.css
- aiida-registry-app/src/Components/MainIndex.jsx
- aiida-registry-app/src/Components/PluginsList.css
- aiida-registry-app/src/Components/PluginsList.jsx
- aiida-registry-app/src/Components/Search.css
- aiida-registry-app/src/Components/Search.jsx
- aiida-registry-app/src/Components/Sidebar.css
- aiida-registry-app/src/Components/Sidebar.jsx
- aiida-registry-app/src/Components/Sort.jsx
- aiida-registry-app/src/Contexts/SearchContext.jsx
- aiida-registry-app/src/Contexts/SortContext.jsx
- Extracted Search, Sort, and related logic into separate components.
- Moved those component into separate files: `Search.jsx`, `Sort.jsx`, `PluginList.jsx`.
- Added project states in `Contexts` folder.
- Extracted the styles of `App.css` into the corresponding components.
- Fixes #266 
`MainIndex` after refactoring:
```
export function MainIndex() {
const { isSearchSubmitted } = useSearchContext();
return (
<main className='fade-enter'>
<GlobalSummary />
<div id='entrylist'>
<h1>
Package list
</h1>
<div className='bar-container'>
<div style={{ flex:'1', marginRight:'10px'}}>
<Search />
</div>
<Sort />
</div>
{isSearchSubmitted === true ? (
<SearchResults />
):(
<PluginsList />
)}
</div>
</main>
);
}
```
> Refactor: Break down MainIndex component into smaller components

- aiida-registry-app/src/App.css
- aiida-registry-app/src/Components/Details.css
- aiida-registry-app/src/Components/MainIndex.css
- aiida-registry-app/src/Components/PluginsList.css
Found this issue after the changes in #267
> Fix design on smaller screens

- aiida-registry-app/src/Components/Details.jsx
The all pass conditioning part can be hit.
> Fix all pass message not shown

- plugins.yaml
Updating developemnt status on aiida-python plugin
> Update aiida-python status

- plugins.yaml
This adds the plugin to the all-electron NAO-based code FHI-aims (https://fhi-aims.org)
> Added aiida-fhiaims plugin

- plugins.yaml
Repos for aiida-gromacs and aiida-amber have been moved from https://github.com/PSDI-Biomolecular-team to https://github.com/PSDI-UK
> Update plugins.yaml for aiida-gromacs and aiida-amber

- plugins.yaml
Added the `aiida-fans` plugin specification to the `plugins.yaml` file.
> Update plugins.yaml with aiida-fans
