plugins.json
Since this plugin was only being used by two developers
the name change of an already registered plugin can be
excused for this one time.
=> Highly unconventional name change of registered plugin

README.md
there should be just one link to click, namely the one leading
to the rendered page
=> remove link to github repo from readme

plugins.json
=> update pip-url for aiida-vasp (after release on PyPi)

plugins.json
The [aiida-plugin-template](https://github.com/aiidateam/aiida-plugin-template) has been superseded by the [AiiDA plugin cutter](https://github.com/aiidateam/aiida-plugin-cutter), which produces [aiida-diff](https://github.com/aiidateam/aiida-diff) by default.
=> replace aiida-plugin-template by aiida-diff

plugins.json
Hi,
I have removed the reference to Vladimir's repo, to simplify maintenance. Also, I removed the explicit "#egg..." spec to avoid having to update the plugins.json file after each upgrade in the repo.
=> Update pip_url in Siesta's record in plugins.json

plugins.json
The initial code has been migrated from the `aiida-core` package where
it was being developed until `v1.0.0b1`
=> Add new in development `aiida-tcod` plugin

plugins.json
aiida-hea plugin:
AiiDA plugin for generating special quasi-random structures by ATAT/sqs and enumerating derivative superstructures by enumlib. 
For High-entropy alloy.
=> new plugin aiida-hea added

make_ghpages/make_pages.py, make_ghpages/requirements.txt, plugins.json
=> Add aiida-core

plugins.json
package_name determines instructions on how to import, i.e. it should be
"aiida", not "aiida_core"
=> fix package name for aiida-core

README.md, make_ghpages/make_pages.py, make_ghpages/mod/templates/main_index.html, make_ghpages/mod/templates/singlepage.html, make_ghpages/requirements.txt, plugins.json
* add tooltips for plugin state development
* switch registration instructions from "development" to "registered"
status
* downgrade some plugins from "development" to "registered" that still had "Diff" stuff in them
* upgrade some of my plugins to "stable" that are being used in production
=> add plugin state dev tooltip

.travis.yml, README.md, make_ghpages/make_pages.py, make_ghpages/mod/templates/singlepage.html, make_ghpages/test_install.py, plugins.json
fix #23
* add installation instructions based on pip_url
* update/fix pip_urls of all packages
* replace http by https
* actually try installing & importing all plugins (except for the ones in `registered` state)
for the moment, this is done in a separate travis job that is allowed to fail
=> fix pip_urls

make_ghpages/mod/templates/base.html, make_ghpages/mod/templates/main_index.html, make_ghpages/mod/templates/singlepage.html
* harmonize display of code homepage and documentation
* entrypoint => entry point
* remove "global summary header"
* main_index: replace "entry" with "package" (as used below)
=> naming issues

.github/workflows/main.yml
it seems that, contrary to travis, github workflows don't remain in
the same directory between steps of a job
See https://github.com/aiidateam/aiida-registry/commit/21f95374adabfb6c4f5569961f84b0256e5a5752/checks#step:4:8
also change time to 23:00 european time.
=> fix directories in github workflow

plugins.json
setup.json of aiida-vasp was taken from develop branch, leading to inconsistency between version displayed on plugin registry and latest release
mentioning @espenfl for info (no action needed)
=> switch source of aiida-vasp setup.json to master

.travis.yml, aiida_registry/fetch_metadata.py, setup.py, tests/__init__.py, tests/test_metadata.json, tests/test_metadata.py
fix #99 
plugin registry was complaining about any entry point that didn't start
with the correct entry point prefix.
we should only be checking entry-point groups defined by AiiDA.
=> check only entry points in aiida groups

.github/workflows/main.yml, aiida_registry/make_pages.py, aiida_registry/mod/templates/main_index.html, aiida_registry/mod/templates/singlepage.html, aiida_registry/static/css/style.css, tests/test_metadata.py
fix #105 
pip won't install pre-releases by default.
if the latest version of a plugin is a pre-release, add --pre option to
pip installation command
Also:
* adapt css style
* add test
=> add --pre to install cmd for pre-release versions

plugins.json
The purpose of aiida-hea is partly duplicated with aiida-alloy. After discuss with the developers of aiida-alloy, I decided to rename aiida-hea to aiida-ce which only contains the plugins in doing the cluster expansion through the [icet](https://icet.materialsmodeling.org/index.html).
I've already started  development and implemented some available features.
=> plugin aiida-hea renamed to aiida-ce

.github/workflows/main.yml
fix #100
it seems like the bug preventing a github actions build from triggering
an update of github pages has been fixed
https://github.community/t5/GitHub-Actions/Github-action-not-triggering-gh-pages-upon-push/m-p/46527#M6555
Re-enabling.
=> re-enable periodic build on github actions

plugins.json
This PR contains brings two changes in `plugins.json`:
* I have developed a new plugin for `ORCA` and added this to the registry. This version works but it is under development to add more parsing options while testing it in real-world calculations. I will activate GitHub actions and put more tests in next few weeks.
* there is a minor change in my other plugin, i.e. `aiida-porousmaterials` where I have added the `pip_url`.
=> adding new aiida-orca + fixing pip_url for aiida-porousmaterials

plugins.json
Plugin for the Standard Solid State Pseudopotentials (SSSP) library.
=> Add new `aiida-sssp` plugin as registered

.github/workflows/main.yml
the problem was that the git checkout no longer contained the 'gh-pages'
branch.
Now fetching all branches as suggested in [1]
[1] https://github.com/actions/checkout#fetch-all-branches
=> fix daily github actions build

plugins.json
Change the status to 'stable' for `aiida-optimize`, `-bands-inspect`, `-symmetry-representation`, `-strain`, and `-tbmodels`.
It seems my editor also formatted the .json - if you mind that I can revert it.
Note that these don't always correspond to the trove classifier currently on PyPI because I haven't had the need to release a new version, but I'll change the trove classifiers to be updated with the next release.
=> Update development status for several plugins.

aiida_registry/__init__.py, aiida_registry/static/css/style.css
CSS for arrow-style lists should apply only to overview page
=> fix style on singlepage

plugins.json
This adds a plugin with a new transport, avoiding the use of SFTP for hosts/clusters that disable it.
=> add sshonly plugin

plugins.json
This plugin provided a scheduler that does not interface to any scheduler installed onto the remote computer. Instead, it interfaces
with the `fireworks` package to allow launching AiiDA CalcJobs to run on the remote computer in a more flexible way. For example, multiple AiiDA jobs can be encapsulated into a single resource allocation (of one or
more computing nodes) to run in serial/parallel.
=> Adding aiida-fireworks-scheduler to the repostiory

plugins.json
Should have used the `raw.github.com` links. Also, apply the fix for `aiida-metavo-scheduler`.
=> Fix plugin_info links

plugins.json
Fixes https://github.com/greschd/aiida-strain/issues/5 ;)
I switched to a simpler "single `trunk` + tags" branching model instead of maintaining separate `master` and `develop`. This means that the `trunk/setup.json` will not always reflect the latest released version on PyPI.
Is this a problem for how the registry operates? I guess this ties into a side discussion from #132 on whether this data should be fetched from PyPI instead of the repositories.
The whitespace change was my editor reformatting JSON, I can revert that if desired.
As a total side note, are these daily builds _supposed to_ run on forks also, or do we need to [add a guard to the `ci.yml` and `webpage.yml`](https://github.com/aiidateam/aiida-quantumespresso/blob/1ad9842942312879c31555693646e8475eaec455/.github/workflows/d …
=> Change branch of aiida-strain to 'trunk'.

aiida_registry/fetch_metadata.py, aiida_registry/make_pages.py
fetch metadata crashed when an exception was encountered during fetch of
the plugin metadata (because `print_exc` actually returns `None`).
=> fix: fetch metadata should not crash

plugins.json
Hi aiidateam, I'd like to register aiida-environ as a plugin (note that the goal of this is to provide continued support for [Environ](https://github.com/environ-developers/Environ), which used to be a part of Quantum Espresso, and as a result, there is existing support for an older version of Environ currently in aiida-quantumespresso). 
Thanks!
=> registered new plugin aiida-environ

README.md, aiida_registry/fetch_metadata.py, plugins.json
fix #191
Since the development status is now parsed from the various
configuration file formats in the plugin repository, duplicating this
information on the registry level leads to misalignment.
The information at the registry level can be dropped - for the moment,
we retain the key in cases where a corresponding trove classifier is not
yet present in the plugin repository (in order not to lose any
information).
=> chore: deprecate `development_status` key

aiida_registry/fetch_metadata.py, plugins.json
also, the web site build should not fail if one of the plugin info files
cannot be found.
=> fix: aiida-diff uses pyproject.toml

aiida_registry/__init__.py, aiida_registry/make_pages.py, tests/static/plugins.yaml, tests/test_basic.py
Contrary to what was described in the README, the implementation choked
when plugins in alpha status were not providing a `pip_url`.
=> fix: do not require pip url for alpha

.github/workflows/ci.yml, aiida_registry/__init__.py, aiida_registry/fetch_metadata.py, aiida_registry/make_pages.py, aiida_registry/test_install.py, bin/aiida-registry, bin/analyze_entrypoints.py, plugins.yaml, setup.py, tests/test_basic.py
For plugins that can be installed successfully, inspect the process
classes provided by them (similar to what `verdi plugin` does) and store
this information in a local json file.
This is in preparation of a more detailed information shown on
the registry.
Also:
- Switch installation tests to aiida-core docker container in order to
get a clean install every time.
=> feat: extract info on calculations/workflows

plugins.yaml
aiida-grouppathx extends the `GroupPath` class in `aiida-core` with `GroupPathX` class.
The latter can be used to represent both `Group` and `Node` instances, allowing a directory-like interface for managing data.
Information: https://github.com/zhubonan/aiida-grouppathx
=> add aiida-grouppathx plugin

plugins.yaml
The plugin has long reached a stable stage. Update this information in the registry accordingly.
=> Update the status of aiida-castep to stable

plugins.yaml
This PR adds `aiida-dataframe`, which contains a Data plugin for `pandas.DataFrame` objects (alpha)
=> Add `aiida-dataframe`

plugins.yaml
For some time I was working on this plugin. It allows running python code as a *CalcJob*. One can create a new CalcJob inhereting class *CalcJobPython*, then overwrite method run_python and everything will be solved by the parent class it self and its corresponding parser so the developer of the derivated package does not have to write special parser. The executable of this derivated ClasJob should be some python instance with some environment.
For better view please look at the example/example.py file or example/example_diagonalization.py. More examples are coming. Even I already am using the package the development is still in alpha stage.
=> Add aiida-python

.github/workflows/ci.yml, .github/workflows/comment.yml, .github/workflows/webpage.yml, .gitignore, aiida_registry/fetch_metadata.py, setup.py
Used github API to get the commits endpoint. This endpoint provides information about each commit. To get the commits count in the last three months. We specify the period in the params of the request and then get the length of the response in this period. which is the commits count.
Get commits count for plugins not hosted on github. Used subprocess module to interact with Git.
First we clone the plugin and then retrieve the commits count in the past three months from it.
This PR needs a github access token to be a repository secret named `TOKEN
=> Sort plugins by the commits count.

.github/workflows/ci.yml, .github/workflows/preview.yml, .github/workflows/webpage.yml, aiida-registry-app/package.json, aiida-registry-app/src/App.css, aiida-registry-app/src/App.jsx, aiida-registry-app/src/main.jsx, aiida-registry-app/vite.config.js, aiida_registry/test_install.py, bin/analyze_entrypoints.py
In this PR, the JSON file is modified to include all the entry points information. and then display it in the `EntryPoints` React component.
I also added a sort feature using two options, alphabetical and commits count. These options can be selected using a dropdown list.
* The `webpage` is slow (~35 min) because it depends on `test-install` workflow where the entry points information is collected. @ltalirz introduced a solution here https://github.com/aiidateam/aiida-registry/pull/240#discussion_r1241079352 but I'm not sure when we need to run the `test-install` and when we don't.
* The description of the inputs/outputs is usually incomplete. 
Not sure if it is an issue with data collection or there is no issue to display it as it is.
=> Display Entry points information & Add Sort feature

aiida_registry/fetch_metadata.py, aiida_registry/parse_pypi.py
Track the changes in the version by comparing it to the current JSON file residing on the `gh-pages` branch.
I open this PR as a draft because the JSON file is not yet there in `gh-pages` (The new page is not merged to `master` yet).
So I set the URL to be the JSON version on my fork (https://raw.githubusercontent.com/AhmedBasem20/aiida-registry/gh-pages/plugins_metadata.json)
for demonstrating but it should be replaced before merging this.
I'm not sure if this method is fine but if there is any good alternative for sorting let me know.
=> Release Sort: Track the change of the plugins version.

.github/workflows/webpage.yml, aiida_registry/fetch_metadata.py
The only use case of putting the data in `master` was to track the release date, and this can be replaced by getting the data from the JSON file in `gh-pages`.
This way we will not need to commit or push the JSON file to any branch since it will be already there in `gh-pages`.
=> Access data from gh-pages branch instead of master

.github/workflows/ci.yml, .github/workflows/preview.yml, .github/workflows/webpage.yml
This includes attempts to speed up the workflow and limit the API calls to github by caching plugins data.
- In `preview.yml` removed the fetch step and use the data that resides in `gh-pages` instead.
- In `ci.yml`, `webpage` created a cache for plugins data and restored it for each step.
- Setup concurrency to the workflow.
=> Cache plugins data.

.github/workflows/ci.yml, .github/workflows/webpage.yml
This PR is from my own repo, so the preview will not run.
This is a good to have change when the PR merge to master, the `preview` should not run.
=> Constraint the running of preview CI only for PR from repo

aiida_registry/__init__.py, aiida_registry/cli.py, aiida_registry/fetch_metadata.py, aiida_registry/make_pages.py, aiida_registry/test_install.py, aiida_registry/utils.py
Allow passing plugin name to `aiida-registry fetch` to accelerate testing locally.
Include some more tidying up on the code
always print errors
extend error/warning to result
Remove unused get_last_fetch_version function
=> Display plugin info fetch failure as error level 

.github/actions/generate-metadata/action.yml
The cache was still not working as expected after I removed all cached data from GH dashboard. After this change, I think it is now caching properly:
- The cache is independent by PRs, for webpage build the caching is always invalid.
- The condition to run metadata generating has one more condition when caching is not hit for none record in the cache database.
=> Using proper caching for plugin metadata

.github/actions/generate-metadata/action.yml, aiida-registry-app/src/Components/Details.jsx
Solve two problems:
1. In `aiida-kkr` the authors emails are stick to one hyperlink.
2. In `aiida-pseudo` and more the author field is empty.
=> Fix multiple author email-to link

aiida_registry/__init__.py, aiida_registry/test_install.py
Narrow down and find the catch is from I call many times of `add_registry_checks` method inside the loop over all plugins.
=> Fix the duplicate error message issue

.github/actions/generate-metadata/action.yml, README.md, aiida-registry-app/src/Components/Details.jsx, aiida_registry/__init__.py, aiida_registry/fetch_metadata.py, aiida_registry/parse_build_file.py, aiida_registry/parse_pypi.py, aiida_registry/test_install.py, aiida_registry/utils.py
In front of every warning and error check message, the link is redirected to the README with the corresponding code number which gives the hint for fixing the issue of the plugin registry.
=> DOC: guide developer to fix registry checks warnings/errors

plugins.yaml
Original repo has been moved from https://github.com/jimboid to https://github.com/PSDI-Biomolecular-team
Plugin has also been added to PyPI
=> Update aiida gromacs plugin information

.github/workflows/ci.yml
fixes https://github.com/aiidateam/aiida-registry/issues/272 to allow pr-preview from forked repo.
=> pr-review from forked repo

plugins.yaml
=> Add aiida-aimall to plugins.yaml

.github/workflows/dev-ci.yml, .github/workflows/plugin-ci.yml, .pre-commit-config.yaml, .pylintrc, aiida_registry/fetch_metadata.py, aiida_registry/parse_build_file.py, pyproject.toml
Fixes https://github.com/aiidateam/aiida-registry/pull/306
The CI action not triggered because the changes are made not from `plugins.yaml` file, thus not trigger the CI. 
The following restriction is set to only trigger the preview CI to prevent the malicious code inject to CI actions. 
https://github.com/aiidateam/aiida-registry/blob/c306d6a7cb85ef12eba51a24d4d3f21805e70b3d/.github/workflows/ci.yml#L10-L11
In this PR, I separate the actions that test changes on other development changes to other CI which will not term out to be a preview from our official aiida official domain. Besides, I remove the pre-commit action and make it triggered from GHA integration.
=> Seperate the dev CI tests to run for dev changes

aiida_registry/__init__.py, aiida_registry/make_pages.py
Web site build broke because one package did not specify pip_url
=> fix: don't choke on missing pip url

plugins.yaml
Regrading issue raised by @giovannipizzi of  appearing W002 for functioning plug-ins.
There are 26 packages that moved from `setup.json` to `pyproject.toml` but haven't updated aiida-registry about this. Currently, 9 of these packages cause W002 to appear on aiida-registry webpage. 
With this commit, errors caused for this reason should disappear. 
Note for future: we (I and @unkcpz) think it's better to have an automated action such, if it doesn't find the info in the plugin_info url, looks for other possibilities, like pyproject.toml, setup.cfg, etc. and once found it could fire a PR for that. If not, drop an email to the responsible plug-in developers about this.
=> Fix on plug-ins who moved from `setup.json` to `pyproject.toml` but haven't updated aiida-registry about this

aiida_registry/test_install.py
From the team, we agree on installing stable released version instead of pre-release version which may include bugs and not the plugin developers intend to show to the community.
=> Update test_install.py install stable version

.github/workflows/dev-ci.yml, bin/analyze_entrypoints.py
`aiida-aimall` show an error that actually can be avoid from `analyse_entrypoint.py`. It raises because it use `default=Int(1)` instead of `default=lambda: Int(1)` that is better in practice (see https://aiida.readthedocs.io/projects/aiida-core/en/latest/topics/processes/usage.html#validation-and-defaults). The point is we should not force developer to do this and the `default=Int(1)` is acceptable. 
So In this PR I just add `aiida.load_profile()` since the profile is exist in the aiida-core-with-servecs image. In the future, we can considered to use the light profile for entry_point analysis.
=> Add load_profile to entrypoints analyse

.github/workflows/dev-ci.yml, bin/analyze_entrypoints.py
Reverts aiidateam/aiida-registry#314
=> Revert "Add load_profile to entrypoints analyse"

.github/workflows/dev-ci.yml, aiida_registry/test_install.py, bin/analyze_entrypoints.py
Reimplemented of #314 with adding a waiting process to make sure the profile is ready.
=> Load profile when running entrypoints check new

plugins.yaml
Adding `aiida-icon`, the (first?) plugin for the weather and climate field. It's being developed at CSCS primarily for C2SM and EXCLAIM, in close cooperation with AiiDA-Team.
=> add aiida-icon plugin to the list

plugins.yaml
Register `aiida-abacus` plugin for [ABACUS](https://abacus.ustc.edu.cn/main.htm) (Atomic-orbital Based Ab-initio Computation at USTC).
=> Register aiida-abacus plugin

plugins.yaml
We changed the name of the `aiida-quantumespresso-hp` plugin to `aiida-hubbard`. The entry point is still fixed to `quantumespresso.hp` as this package provides the plugin for the HP code of Quantum ESPRESSO.
=> Update plugin name for aiida-quantumespresso-hp
